name: GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir -p docs
          cp -R base.css base.js components contato database home imagens itens-da-loja lista-de-desejo modelo.html produto-individual sobre docs/

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: docs
